### ISSUE TITLE
github.com/nats-io/nats.go        1.20.0 -> 1.21.0

### ISSUE THREAD

**Issue by gedw99** [oderwat/go-nats-app#1]
The 1.21.0 version is out.
would allow NATS TLS to work ?

**Comment by gedw99** [comment]
Seems the upgrade works.

**Comment by oderwat** [comment]
It should. I use it with a PWA that connects to our real NATS cluster.

**Comment by oderwat** [comment]
I just added some of my internal documentation in [2]. I saw you collect some info about NATS. So, that may be of interest. Vielleicht kannst Du es ja brauchen :)

**Comment by gedw99** [comment]
> I just added some of my internal documentation in #2. I saw you collect some info about NATS. So, that may be of interest. Vielleicht kannst Du es ja brauchen :)

Perfect. Yeah JSON Schema approach of he NATS team is pretty slick.

**Comment by gedw99** [comment]
> It should. I use it with a PWA that connects to our real NATS cluster through 'wss' with the same dialer code.
> 
> This is the main part that makes it possible by letting nats.go know, that the TLS handshake already was done.
> 
> ```
> func (cw WasmNatsConnectionWrapper) SkipTLSHandshake() bool {
> 	return true
> }
> ```

thanks ! that's exactly what i was about to do also..

Will PR back if i see anything..
