### ISSUE TITLE
Some useful Go packages that are related to using NATS for PWAs

### ISSUE THREAD

**Issue by oderwat** [oderwat/go-nats-app#2]
# Some useful packages

## JSON Schema

I think about documenting our services with JSON Schema as part of the service code itself.

The NATS Developers do. Try:

- `nats schema search`
- `nats schema info io.nats.jetstream.api.v1.account_info_response | jq .`

|What is it| URL | Comment |
|---|---|---|
|jsm.go a library to manage and interact with JetStream | https://github.com/nats-io/jsm.go | Contains a validator and their registry code |
|JSON Schema from Go Struct | https://github.com/invopop/jsonschema | |
|JSON Schema Validator | https://github.com/xeipuuv/gojsonschema | |
|Yaml marshalling and unmarshalling | https://github.com/invopop/yaml| To convert between Yaml and JSON |

**Comment by gedw99** [comment]
if you want you can also use the golang jq:

``` 
go install github.com/itchyny/gojq/cmd/gojq@latest

nats schema info io.nats.jetstream.api.v1.account_info_response | gojq .
```

**Comment by oderwat** [comment]
We actually moved to use AVRO with our own "X" tension: https://github.com/metatexx/avrox
