### ISSUE TITLE
Please assist with TLS config

### ISSUE THREAD

**Issue by brucebotes** [oderwat/go-nats-app#6]
@oderwat ,
May I request guidance and/or advice getting the secure websocket (wss://) connection to work with the embedded nats server. Below is my attempt. I tried numerous attempts but to no avail. I am missing something major in my understanding in my very limited knowledge of TLS certs. I do know they certs work - tested with an other go app (gorilla websockets). My ISP enabled 80/433/3000/4000 ports. 

Thank you in advance.

package back

import (
	"bytes"
	"compress/flate"
	"context"
	"crypto/tls"
	"encoding/base64"
	"fmt"
	"image"
	"image/jpeg"
	"log"
	"net"
	"net/http"
	"net/url"
	"os"
	"os/signal"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/go-chi/chi/v5/middleware"
	"github.com/maxence-charriere/go-app/v9/pkg/app"
	"github.com/nats-io/nats-server/v2/server"
	"github.com/nats-io/nats.go"
	"github.com/o1egl/govatar"
	"golang.org/x/net/netutil"
)

// AppServer implements the Backend service
type AppServer struct {
	mux *chi.Mux
}

func (srv *AppServer) Mux() *chi.Mux {
	return srv.mux
}

type Muxer interface {
	Mux() *chi.Mux
}

func Create(ah *app.Handler) {
	var srv AppServer
	cert, err := tls.LoadX509KeyPair(
		"mysite.com/combined_certificate.pem",
		"mysite.com/certificate-key.pem",
	)
	if err != nil {
		log.Fatal(err)
	}
	tlsConfig := &tls.Config{
		Certificates:       []tls.Certificate{cert},
		ServerName:         "mysite.com",
		InsecureSkipVerify: true,
	}

	opts := &server.Options{
		ServerName:     "Your friendly backend",
		Host:           "127.0.0.1",
		Port:           8501,
		NoLog:          true,
		NoSigs:         true,
		MaxControlLine: 4096,
		Accounts: []*server.Account{
			{
				Name: "cluster",
			},
		},
		Websocket: server.WebsocketOpts{
			Host:       "127.0.0.1",
			Port:       3000,
			NoTLS:      false,
			TLSConfig:  tlsConfig,
			SameOrigin: true,
			AllowedOrigins: []string{
				"wss://mysite.com",
				"wss://mysite.com:3000",
				"wss://www.mysite.com",
				"wss://www.mysite.com:3000",
				"https://mysite.com",
				"https://mysite.com:3000",
				"https://www.mysite.com",
				"https://www.mysite.com:3000",
			},
			Compression:      false,
			HandshakeTimeout: 5 * time.Second,
		},
		DisableShortFirstPing: true,
	}
	// Initialize new server with options
	ns, err := server.NewServer(opts)
	if err != nil {
		panic(err)
	}

	// Start the server via goroutine
	go ns.Start()

	// Wait for server to be ready for connections
	if !ns.ReadyForConnections(2 * time.Second) {
		panic("could not start the server (is another instance running on the same port?)")
	}

	fmt.Printf("Nats AppServer Name: %q\n", ns.Name())
	fmt.Printf("Nats AppServer Addr: %q\n", ns.Addr())

	// Connect to server
	nc, err := nats.Connect(ns.ClientURL())
	if err != nil {
		panic(err)
	}

	// This is the chat broker
	_, err = nc.Subscribe("chat.say", func(msg *nats.Msg) {
		fmt.Printf("Got: %q\n", msg.Data)
		err = nc.Publish("chat.room", msg.Data)
		if err != nil {
			panic(err)
		}
	})
	if err != nil {
		panic(err)
	}

	_, err = nc.Subscribe("govatar.female", func(msg *nats.Msg) {
		if err != nil {
			panic(err)
		}
		var img image.Image
		// always female and random
		img, err = govatar.Generate(govatar.FEMALE)
		if err != nil {
			panic(err)
		}
		var buf bytes.Buffer
		err = jpeg.Encode(&buf, img, &jpeg.Options{Quality: 80})
		if err != nil {
			panic(err)
		}
		err = msg.Respond([]byte("data:image/jpeg;base64," + base64.StdEncoding.EncodeToString(buf.Bytes())))
		if err != nil {
			log.Printf("Respond error: %s", err)
		}
		// noErr(err)
	})
	if err != nil {
		panic(err)
	}

	r := chi.NewRouter()
	srv.mux = r

	r.Use(middleware.CleanPath)
	r.Use(middleware.Logger)
	compressor := middleware.NewCompressor(flate.DefaultCompression,
		"application/wasm", "text/css", "image/svg+xml" /*, "application/javascript"*/)
	r.Use(compressor.Handler)
	r.Use(middleware.Recoverer)

	listener, err := net.Listen("tcp", ":443")
	if err != nil {
		panic(err)
	}

	mainServer := &http.Server{
		Addr:      listener.Addr().String(),
		TLSConfig: tlsConfig,
	}

	// try to build the final browser location
	hostURL := url.URL{
		Scheme: "https",
		Host:   mainServer.Addr,
	}

	log.Printf("Serving at %s\n", hostURL.String())

	// This is the frontend handler (go-app) and will "pick up" any route
	// which is not handled by the backend. It then will load the frontend
	// and navigate it to this router.
	srv.mux.Handle("/*", ah)

	// registering our stack as the handler for the http server
	mainServer.Handler = srv.Mux()

	// Creating some graceful shutdown system
	shutdown := make(chan struct{})
	go func() {
		listener = netutil.LimitListener(listener, 100)
		defer func() { _ = listener.Close() }()

		err := mainServer.ServeTLS(listener, "", "")
		if err != nil {
			if err == http.ErrServerClosed {
				fmt.Println("AppServer was stopped!")
			} else {
				log.Fatal(err)
			}
		}
		// when run by "mage watch/run" it will break mage
		// before actually exiting the server, which just looks
		// strange but is okay after all
		// time.Sleep(2 * time.Second) // just for testing
		close(shutdown)
	}()

	// Setting up signal capturing
	stop := make(chan os.Signal, 1)
	signal.Notify(stop, os.Interrupt)
	// Waiting for SIGINT (kill -SIGINT <pid> or Ctrl+c )
	<-stop
	shutdownServer(mainServer, shutdown)
	fmt.Println("Program ended")
}

// shutdownServer stops the server gracefully
func shutdownServer(server *http.Server, shutdown chan struct{}) {
	fmt.Println("\nStopping AppServer gracefully")
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()
	fmt.Println("Send shutdown!")
	if err := server.Shutdown(ctx); err != nil {
		log.Fatal(err)
	}
	fmt.Println("Waiting for server to shutdown!")
	<-shutdown
	fmt.Println("AppServer is shutdown!")
}

**Comment by oderwat** [comment]
Well, if your backend uses TLS and you could verify that it works, the question remains if you use the correct setup for the client, which means that you need to use a custom dialer and add the SkipTLS option when connecting. We had the NATS guys add this option to the go-client library. We also published some code that can be used with and without TLS websockets: [natswasm.go](https://github.com/metatexx/mxx/blob/main/natswasm/natswasm.go).

If you still have problems, you may need show more of your code, so we could actually compile it and try to get it to work.

**Comment by brucebotes** [comment]
Thank you for your assistance. Much appreciated!!!!

I checked and do believe I am using the custom dialer correctly. But heck
something is surely wrong with my understanding. And I would like it to
work - core design pattern

I am not confident with pull-requests etc. So I did it my way. I checked
out a clone of the original master branch (yours) and created a new "
*test" *branch.
A folder contains the certs *I know I should not do this. But the domain is
my test domain.*

You can find the code here:
 https://github.com/brucebotes/go-nats-app.git

Please browse and see if I missed something. You are very familiar with the
code ...

Many thanks.

**Comment by oderwat** [comment]
I got your version to run. But I had to replace the domain and certificates and such. We usually use a domain that resolves to a local address, like "local3.somedomain.com" that resolves to 127.0.0.3 (in this case) because 127.0.0.1 usually is taken by stuff on our machines. But anyway.

You should first check if you can use `nats --server wss://thedomain.dom:3000 sub test` and see if that connects and works. It did for me. However, the website still did not work. I was struggling and did not understand what was going wrong until added "Proxyman" in the middle just to see that the request actually ends up with a 403 (which is not displayed anywhere when debugging, afais). As the nats-cli client is connecting, it was clear that it has to do with the browser (as usual).

I made the following modification which made it work:

```
SameOrigin: false,
AllowedOrigins: []string{},
```

So it has to do with the same origin policy. I was too tired to figure out what the origin should be. Anything "sane" did not work. I have to confess that I do not need where it fails and that I had to debug all the code. We use an external NATS cluster, and it uses the distributed access model (JTW+NKey) to make sure that only allowed clients can connect.

**Comment by brucebotes** [comment]
Hans, I am SO GRATEFUL for your assistance. I really have limited knowledge
working with TLS/SSL. Nats is also relatively new to me - although I have
used it in the past with a micro service training course - Stephen Grider
on Udemy. Wonderful stuff.

I agree, when I commented the embedded part out and used an external
instance of nats.io, it worked. But it is important for me to have it
embedded, even the web assets into a single file. I want to enhance my
chances for hosting - maybe fly.io.

Thus there is interaction between the net/http code when embedding. I will
look into the local3.samedomain.com concept. I now know the issue is not
the code ( or a bug in nats) but the topology of the domains etc which I
have no idea off....

Nevertheless, THANK you for the great example and support in the open
source space. We really appreciate  your contribution to enhance and expand
our competency in the real world.

**Comment by oderwat** [comment]
Did it not work, when you remove the same origin check? I think it should. 

You may want to check out: https://github.com/mlctrez/go-nats-app, he added a proxy into the formula to have the same origin for the HTTP and web server, like it is in a traditional setup.

But I also would not recommend having the internal NATS server. You can create a cluster on fly.io (see: https://github.com/fly-apps/nats-cluster/) (EDIT: Maybe not, they say it is only available internal) or just use NGS (https://docs.synadia.com/ngs/guides). 

Running a single NATS server on a cheap VPS can also be an option. Having three of them can serve a fairly significant number of users, too. I believe you can create that for less than $20 a month, and it may host some DB and other stuff too if needed. It is never too early to learn a bit about hosting.

For the client, there is not really a difference where the NATS server is running. It would be more important to have the backend data (DBs, for example) on the same machine as the services and the Nats-Server. So you do not end up with a lot of RTT between them.

The reason to work with an integrated NATS server that we have is running a leaf-node with the whole server deployed on a client computer. For example, by using WebView to create an executable that runs the app on Windows or OSX. The integrated NATS server will then contact the cluster and is used to store data locally without the need to go over the network, but still be able to use NATS for the processing of all data. One could also use the internal NATS server to simplify conversation between the frontend and the backend in an isolated app.

**Comment by brucebotes** [comment]
Thank you so much. No, unfortunately I could not get it to work :(.

I will be exploring/testing the mlctrex reverse proxy approach ( based on
gin - I am a chi fan) simply for learning and better understanding. Just
maybe, I can get the TLS to work...

But I have come to a similar conclusion. I will opt for the decentralised
approach. Yea, I will have to manage TLS certs at more than one location,
not too much of a risk these days. Sharing TLS and addressing network
configs is hard.

There is very little effort and less complexity going for the external
approach. The Nats strengths are simplicity and robustness (QoS) and
embedding the server may compromise its strengths which I am experiencing.
Not a good idea. It is very difficult to ring fence when there are issues.

I get the reasoning for the embedded approach and leaf-nodes, makes a lot
of sense for "off-line" modes  and recovery etc. Let Nats figure that out.
Having a Nats client in the WASM service of a PWA is also a fantastic idea.
It fascinated me,

Again thank for valuable time and assistance. Most appreciated.

Ps the fly.io nats-cluster looks very promising, co hosting. Thank you for
info,

**Comment by brucebotes** [comment]
Hi Mr *Oderwat*.
Well done and thank you for your advice and support. (This includes
https://github.com/mlctrez/go-nats-app, from  *mlctrez*
<https://github.com/mlctrez>) and there is the go-app from *maxence-charriere
(*https://github.com/maxence-charriere/go-app).

The TLS works really well with the proxy and the embedded Nats Server. It
like  having 4+ components in one,

   1. Web server - backend
   2. Embedded frontend
   3. Embedded Nats server
   4. Embedded Caddy. (reverse proxy)
   5. "and the bonus - a PWA with WASM - thank you Maxence and Hans for
   go-app

A huge learning curve for me! Awesome stuff!. I cannot thank all of you
enough.

I do agree that it is not ideal, but this does give me an edge for a very
powerful and manageable proposition. Easy devops etc.

Thank you Hans for your guidance, I am lost for words.
