### ISSUE TITLE
A very weird problem

### ISSUE THREAD

**Issue by suntong** [oderwat/go-nats-app#7]
Hi @oderwat, I'm experiencing a _very weird_ problem that need your help.

Please take a look at this minimum change that I made to the code:
https://github.com/suntong/go-nats-app/commit/44d30b9007b7c9a3342c55a7181bafacf4bb957a

IE, for the lines in
https://github.com/suntong/go-nats-app/blob/master/front/front.go#L141-L146

```go
		app.Range(uc.messages).Slice(func(i int) app.UI {
			//return app.Div().Text(uc.messages[len(uc.messages)-1-i])
			id := len(uc.messages) - 1 - i
			app.Logf("chat[%d]: %s\n", id, uc.messages[id])
			return &CodeBlock{code: uc.messages[id], id: fmt.Sprintf("chat%02d", id)}
		}),
```

If I uncomment the `return` statement, then everything is good.
Commenting it out, I'll get something like this:

![image](https://github.com/oderwat/go-nats-app/assets/422244/c7c62ec4-48d7-42d5-bc09-fc97cf2bb7e7)

IE, it is repeating only the 1st message, while the `app.Logf` shows that the `CodeBlock` assignment is done right. 

What could possible be happened? It's almost looks like the well known "Referencing a loop variable later" problem ([here](https://levelup.gitconnected.com/4-pitfalls-in-go-i-still-occasionally-fall-into-7099eae3ecd1), the top one), however, the same code works fine in my other example:

https://github.com/suntong/go-app-demos/blob/master/0B2A-codecopy/main.go#L47-L51

They both looks exactly the same to me. What makes the huge difference? I think it is more an architect problem that only you can find the answer. please help. thx.

**Comment by oderwat** [comment]
> `&CodeBlock{code: uc.messages[id], id: fmt.Sprintf("chat%02d", id)}`

Needs to be: `&CodeBlock{Code: uc.messages[id], ID: fmt.Sprintf("chat%02d", id)}` or the component is not getting initialized with your data.

**Comment by suntong** [comment]
> or the component is not getting initialized with your data.

hmm..., where does such requirement come from?   
(last time having exported variables gave me problem and only using none-exported variables fixed the problem)

Moreover, why 
https://github.com/suntong/go-app-demos/blob/master/0B2A-codecopy/main.go#L47-L51
works using _none-exported_ variables _as-is_ without any issue?

**Comment by oderwat** [comment]
Your other example has the data in the components created at once (when it is rendered the first time). With the Go-App-NATS, you do not have the data beforehand. Then the first gets added (which creates the first node), then the second and so on. Those additional nodes then are added through the updates and backwards. This means that when a node is added, all the nodes need to be updated (because 0 gets the content of 1 and 1 gets to be what was the content of 0 before).

Use lower-case on the "go-app-nats" again and add `uc.messages = []string{"first", "second"}` to `OnInit()` and you will see that these are rendered "as expected" but the later ones are not.

```
func (uc *appControl) OnInit() {
	app.Log("OnInit")
	uc.whoami = namegenerator.NewNameGenerator(time.Now().UTC().UnixNano()).Generate()
	// a blank image
	uc.avatar = "data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7"
	uc.messages = []string{"first", "second"}
}
```

Then change your "example"'s init to:

```go
func (m *codeBlockModel) OnInit() {
	go func() {
		time.Sleep(time.Second)
		m.code = []string{`
                    // Code block 1
                    function helloWorld() {
                        console.log("Hello, world!");
                    }
`}
		m.Update()
	}()

	go func() {
		time.Sleep(2 * time.Second)
		m.code = append(m.code, `
                    // Code block 2
                    for (let i = 0; i < 5; i++) {
                        console.log(i);
                    }
`)
		m.Update()
	}()
}
```

The you will see that it breaks the same way.

**Comment by oderwat** [comment]
And don't believe that I knew that before debugging it xD ... The stuff is mind-bending at times, but I got some experience with situations like this, and that makes me find the problem with some experimenting. I'm still learning myself. That is why I take the "challenges" and try to figure out what is going on (when I do not know it anyway, of course).

**Comment by suntong** [comment]
> Your other example has the data in the components created at once (when it is rendered the first time). With the Go-App-NATS, you do not have the data beforehand.

Wow, I would have never been able to imagine that 

- the problem actually comes from such angle, and
- the fix would be using the exported variables

> where does such requirement come from?
> (last time having exported variables gave me problem and only using none-exported variables fixed the problem)

I thought over and over the explanation you gave, although I'm still not totally understand it yet, I think I kind of understand why using the exported variables can fix the issue. 

I think it is just the reverse of what I had experienced -- previously I need to _alter_ the variable values after it has been created, whereas now I need to _keep_ the variable values as its creation without being altered later on.

Thanks again for taking the time fixing it and then explaining it in details.  
Really appreciate it, and Kudos to your deep deep knowledge and this wonderful piece of demo code.

FTA, in case it might help anyone else.

- to replicate the problem: [data added step by step](https://github.com/suntong/go-app-demos/commit/c0939d2adf8623f85dae7f6fafd297464bb273f6)
- to [fix the previous hidden problem](https://github.com/suntong/go-app-demos/commit/ba95052dc522e523632b82e5e64b766723b0662f)
