### ISSUE TITLE
Use golang std lib for http , instead of chi ?

### ISSUE THREAD

**Issue by gedw99** [oderwat/go-nats-app#9]
Removing chi should make the binary smaller in theory .. 

Instead use the http std lib in go 1.21  and up .

what’s your thoughts ?

btw thanks for the upgrades ..

**Comment by oderwat** [comment]
Well, I do not really care much about backend program size, and you need to replace the middlewares.

**Comment by gedw99** [comment]
Will close then . Thanks for the response @oderwat
